version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_CREATE_TOPICS: "scheduled_report_queue:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafdrop:
    build:
      context: .
      dockerfile: kafdrop.docker
    image: arvindn05:kafdrop
    ports:
      - target: 9009
        published: 9009
        protocol: tcp
        mode: host
    environment:
      ZK_HOSTS: zookeeper:2181
      LISTEN: 9009
    depends_on:
      - zookeeper
      - kafka